# Generated by Django 6.0.3 on 2026-03-23 22:14

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=dashboard.models.generate_api_key, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Project name for this key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_tag', models.CharField(max_length=100)),
                ('experiment_number', models.IntegerField()),
                ('commit_hash', models.CharField(blank=True, default='', max_length=40)),
                ('parent_commit_hash', models.CharField(blank=True, default='', max_length=40)),
                ('metric_name', models.CharField(blank=True, default='', max_length=100)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('secondary_metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('keep', 'Keep'), ('discard', 'Discard'), ('crash', 'Crash')], default='running', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('diff', models.TextField(blank=True, default='')),
                ('timeout_seconds', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='dashboard.apikey')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
