# Generated by Django 6.0.3 on 2026-03-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Project configuration from autoresearch.yaml'),
        ),
    ]
